### PR TITLE
blasr to support bam concordant

### PR DESCRIPTION
**Pull request by ylipacbio**

### CODE REVIEW

**Comment by ylipacbio** [comment]
blasr and blasr_libcpp to support bam concordant.

**Comment by ylipacbio** [comment]
oops my write access to pi been revoked?

**Comment by ylipacbio** [comment]
**Please grant me write access so that I can update blasr_libcpp and blasr.**

**This commit will break bax2bam, which should be fixed by P4 shelved changelist 163149**

**Comment by pb-cdunn** [comment]
This is not used anymore. Lance said he was able to work-around you `p4 diff` problem in **pb-git**, yes?

**Pull request closed without merging**
