### PR TITLE
Revert "Add pbccs"

### PR DESCRIPTION
**Pull request by pb-cdunn**
Reverts PacificBiosciences/pi#3

### CODE REVIEW

**Comment by pb-cdunn** [comment]
Actually, no-one has pulled this yet, so I'll just rebase it away...

**Comment by pb-cdunn** [comment]
Ok. You have 2 copies of gmock, when really it could be pulled as an artefact. But the bigger problem is seqan.
```
$ du -s seqan-library-2.0.0/*
13260   seqan-library-2.0.0/include
27128   seqan-library-2.0.0/share
```
The includes could be reduced by pulling a tarball at build-time. Possibly we should just let seqan be another submodule? But the biggest single problem is the html directory under share/doc/seqan/html. Simply removing that and rebasing the whole repo (manually, or using git-filter-branch) would save more than half.

It may not seem like a big deal, but I've seen this before. People learn the benefits of git, but ignore the achilles heel: large files (and large numbers of files). If we add a few repos of this size, then people will start to complain about how long the initial clone takes.

**Comment by nlhepler** [comment]
I'd love to let seqan be another submodule, even one pruned of unnecessary documentation for speed reasons.

**Comment by nlhepler** [comment]
As for 2 copies of gmock, that's not going to go away in the immediate future, I think, because ConsensusCore is a subtree to allow faster development of that library with pbccs, but it will get refactored back out into the PacificBiosciences/ConsensusCore repo when that work has stabilized. I'm happy to make a branch that does away with/something to gmock and seqan, but you're going to have to help me with how you want that structured--I'm not going to push it to master until I'm sure it's not going to impede Nigel's development work.

**Comment by nlhepler** [comment]
Actually, I just had pbccs point to ConsensusCore's copy--happy to leave that there. I'm going to remove the seqan-library-2.0.0/share -- we can then rebase the whole thing at that point.

**Comment by pb-cdunn** [comment]
#### Preconditions
You have some things to do before you can use **pivc**.

1. Find a way to fetch private repos (from Jenkins, Swarm, releasebuild, etc.).
1. Write `mobs.ish` for **pbccs*.
    * This is non-trivial. blasr is a poor example, but there are others. Ask Herb.
1. Create a Perforce directory and update pb-sync and releasebuild. (I can do this part for you in a few minutes.)

After that, you have your own integration-package, and you can do whatever you want with it, aside from possible complaints about the 25s it takes to clone your repo.

#### Next phase
To get into **pi** (or to reduce initial cloning delays), there are a few more requirements.

1. Split all dependencies into their own repos.
    * Some might even turn into tarballs.
1. Write `mobs.ish` for *each* repo.
   * Even third-party tarballs need this.
1. Rename something other than **pbccs**, reduce history, and prune.
    * That way, when you get around to reducing the diskspace requirements for one, you can use a *new* repo, so old Perforce CNs will continue to build successfully.

**Comment by pb-cdunn** [comment]
`--depth=1` does not seem to help much.
```
$ time git submodule update --init --depth=1
Submodule 'pbccs' (git@github.com:PacificBiosciences/pbccs.git) registered for path 'pbccs'
Cloning into 'pbccs'...
remote: Counting objects: 973, done.
remote: Compressing objects: 100% (643/643), done.
remote: Total 973 (delta 338), reused 931 (delta 315), pack-reused 0
Receiving objects: 100% (973/973), 2.54 MiB | 19.00 KiB/s, done.
Resolving deltas: 100% (338/338), done.
Checking connectivity... done.
Submodule path 'pbccs': checked out '7294cbef9b9d701ee7812b58742438be2f807619'

real    0m30.356s
```
I've also seen it as fast as 9s, but that's still not great. With git-2.1, I measured about 20s. So restricting the depth does not help much. Updating later is cheap:
```
$ time git fetch --depth=1000
remote: Counting objects: 421, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 421 (delta 266), reused 389 (delta 235), pack-reused 0
Receiving objects: 100% (421/421), 46.57 KiB | 0 bytes/s, done.
Resolving deltas: 100% (266/266), completed with 53 local objects.

real    0m2.002s
```

And this is all with your *latest* pbccs, after dropping part of seqan.

I think the real problem is this:
```
$ find . | wc
    973     973   62958
```
Too many files!

I've verified this theory by forking your repos and removing the third-party directory. I did *not* rebase or filter. Just rm, commit, and push.
```
$ time git submodule update --init --depth=1
Submodule 'pbccs' (git@github.com:pb-cdunn/pbccs.git) registered for path 'pbccs'
Cloning into 'pbccs'...
remote: Counting objects: 261, done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 261 (delta 94), reused 215 (delta 65), pack-reused 0
Receiving objects: 100% (261/261), 626.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (94/94), done.
Checking connectivity... done.
Submodule path 'pbccs': checked out 'fb327a7145791d3c023bc63717f5de2925225ccc'

real    0m4.224s
```
So you simply have too many files and/or directories. Even untar would be a bit slow. The problem might actually be our filesystem...

Yeah, that's a big part of it. Times drop by about 50% in /tmp, in multiple scenarios. (--depth=1 helps, but less reliably.)

Anyway, this is only a problem the first time you checkout.

**Comment by pb-cdunn** [comment]
Our slow filesystem is an issue for DALIGNER too.

**Pull request closed without merging**
